import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const gothamRounded = localFont({
    src: [
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_light.otf",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_lightitalic.otf",
            weight: "300",
            style: "italic",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_book.otf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_bookitalic.otf",
            weight: "400",
            style: "italic",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_medium.otf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_mediumitalic.otf",
            weight: "500",
            style: "italic",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_bold.otf",
            weight: "700",
            style: "normal",
        },
        {
            path: "../../public/fonts/gotham-rounded/gothamrnd_bolditalic.otf",
            weight: "700",
            style: "italic",
        },
    ],
    variable: "--next-font-gotham-rounded",
});

const inter = Inter({
    subsets: ["latin"],
    variable: "--next-font-inter",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${gothamRounded.variable} ${inter.variable}`}>
            <body className={`bg-primary py-4 text-white antialiased`}>{children}</body>
        </html>
    );
}
